spring:
  application:
    name: minijira

  datasource:
    url: jdbc:postgresql://localhost:5432/minijira
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: imakepie1

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true